### ISSUE TITLE
What GPU is used for training?

### ISSUE THREAD

**Issue by ramtiin** [Sxela/ArcaneGAN#22]
Hi,

I want to train the Fastai u-net model. However, when I try to train the critic  (`learn_critic.fit_one_cycle(6, 1e-3)`), I get the following error:

`CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 14.76 GiB total capacity; 9.78 GiB already allocated; 891.75 MiB free; 12.57 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

The GPU is a Tesla T4 with 16 GB of VRAM. My batch size is 4 and the training images size is 512*512. I also tried with lower numbers, but I'm still getting the same error.

**Comment by Sxela** [comment]
Hi! With 16 gigs I've managed to get as high as 400x400 with batch size 2-4.
Possible tips: if you run out of memory, it's best to restart the session, and resume from the failed step, because once you've got an OOM, even if you lower the settings in the same session, the cache is still there using memory.
You can also try using smaller models, i.e. resnet18 encoder for unet, smaller nf for the critic (check the critic constructor function)

**Comment by ramtiin** [comment]
Thanks! I solved the problem with these settings: bs=1, size=512, and bs=4, size=400.
However, with this batch size, training requires so much time.

Also, it's important to run the following code to clear the GPU memory:
```
learn_gen=None
gc.collect()
```

Could you let me know some information like the size, learning rate, and the number of steps you used for training ArcaneGAN?
